name: GraalVM Native Image build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fileName: httpx-linux-x86_64
            file: target/httpx
          - os: windows-latest
            fileName: httpx-windows-x86_64.exe
            file: target/httpx.exe
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "23.0.0"
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: GraalVM native image build
        run: mvn -Pnative -DskipTests clean package
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: ${{ matrix.file }}
          args: "-7"
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.fileName }}
          path: ${{ matrix.file }}

  build-without-upx:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            fileName: httpx-osx-x86_64
            file: target/httpx
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "23.0.0"
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: GraalVM native image build
        run: mvn -Pnative -DskipTests clean package
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.fileName }}
          path: ${{ matrix.file }}